name: conviction-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - numpy=1.24.4
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - xgboost=1.7.6
  - shap=0.42.1
  - boto3=1.28.17
  - pyyaml=6.0.1
  - pip:
    - sagemaker==2.176.0
    - awscli==1.27.167
    - lightgbm==4.1.0
    - catboost==1.2.2
    - optuna==3.4.0
    - tqdm==4.65.0
    - python-dotenv==1.0.0
    - requests==2.31.0
    - psutil==5.9.5
    - pytest==7.4.0
    - pytest-cov==4.1.0
