{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "conviction-ai-pipeline.fullname" . }}-sm
  labels:
    {{- include "conviction-ai-pipeline.labels" . | nindent 4 }}
    release: prometheus
    component: monitoring
spec:
  selector:
    matchLabels:
      {{- include "conviction-ai-pipeline.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheus.scrapeInterval }}
      scrapeTimeout: {{ .Values.prometheus.scrapeTimeout }}
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'pipeline_.*'
          action: keep
{{- if .Values.chaos.exporter.enabled }}
    - port: metrics
      path: /metrics
      interval: 15s
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'chaos_.*'
          action: keep
{{- end }}
{{- end }}
