apiVersion: v1
kind: Service
metadata:
  name: {{ include "conviction-ai-pipeline.fullname" . }}
  labels:
    {{- include "conviction-ai-pipeline.labels" . | nindent 4 }}
    component: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    {{- if .Values.prometheus.enabled }}
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "conviction-ai-pipeline.selectorLabels" . | nindent 4 }}
    component: pipeline